drop table post;

CREATE TABLE POST(
    ID NUMBER(6) GENERATED ALWAYS AS IDENTITY,
    TITLE VARCHAR2(100),
    CONTENT VARCHAR2(2000),
    MEMBER_ID NUMBER(6)
);

INSERT INTO POST(TITLE,CONTENT,MEMBER_ID)
VALUES('POST_TEST','CONTENT_TEST',41);

COMMIT;