CREATE TABLE MEMBER (
    ID NUMBER(6) GENERATED ALWAYS AS IDENTITY,
    USERNAME VARCHAR2(15),
    EMAIL VARCHAR2(30),
    PASSWORD VARCHAR2(30)
);

INSERT INTO MEMBER(USERNAME,EMAIL,PASSWORD)
VALUES('donggil','dongmail@gmail.com','donggil1234');

COMMIT;